
# docker-compose.yml untuk Next.js IoT Multimedia Dashboard
version: '3.8'

services:
  # Next.js application
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: iot-multimedia-dashboard
    container_name: iot-multimedia-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - iot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  iot-network:
    driver: bridge